/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package booking;

import static booking.LoginForm.currentUser;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gitu
 */
public class ManageCottageForm extends javax.swing.JFrame {

    private Connection con = MySqlConnection.myConnection();
    private ResultSet rs;
    
    /**
     * Creates new form AddCottageForm
     */
    public ManageCottageForm() {
        initComponents();
        displayRecords();
        customInit();
    }
    
    private void customInit() {
        btnEdit.setEnabled(false);
        tblCottageRecords.getTableHeader().setFont(new Font("Corbel", Font.PLAIN, 16));
    }
    
    private void clearTextboxes() {
        txtCottageId.setText(null);
        txtCottageName.setText(null);
        txtNumOfRooms.setText(null);
        txtAvailability.setText(null);
        
        String userRole = currentUser.getRole().toLowerCase();
        switch (userRole) {
            case "admin":
            case "general":
                btnEdit.setEnabled(false);
                btnEdit.setBackground(new Color(240, 240, 240));
                btnAdd.setEnabled(true);
                btnAdd.setBackground(new Color(105, 205, 130));
                break;
            case "audit":
                btnEdit.setEnabled(false);
                btnEdit.setBackground(new Color(240, 240, 240));
                btnAdd.setEnabled(false);
                break;
        }
    }
    
    private ArrayList<Cottage> getCottagesList() {
        ArrayList<Cottage> cottageList = new ArrayList();
        try {
            Statement st;
        
            String query = "SELECT * FROM `cottage`";
            st = con.createStatement();
            rs = st.executeQuery(query);
            
            Cottage cottage;
            while (rs.next()) {
               cottage = new Cottage(rs.getInt("cottage_id"), rs.getString("cottage_name"), rs.getInt("num_of_rooms"), 
                       rs.getBoolean("is_available"));
               cottageList.add(cottage);
            }
        }
        catch (Exception ex) {
            System.out.println("Error. " + ex);
        }
        return cottageList;
    }
    
    private void displayRecords() {
        ArrayList<Cottage> list = getCottagesList();
        DefaultTableModel model = (DefaultTableModel)tblCottageRecords.getModel();
        if (list.size() != 0) {
            model.setRowCount(0);
            Object[] col = new Object[4];
            for (int i=0; i<list.size(); i++) {
                col[0] = list.get(i).getCottageId();
                col[1] = list.get(i).getCottageName();
                col[2] = list.get(i).getNumOfRooms();
                col[3] = list.get(i).getAvailability();

                model.addRow(col);
            }
        } else {
            String noRecords = "No Records.";
            model.setRowCount(0);
            Object[] col = new Object[1];
            col[0] = noRecords;
            
            model.addRow(col);
        }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCottageId = new javax.swing.JTextField();
        txtCottageName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumOfRooms = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCottageRecords = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel1.setText("Cottage ID");

        txtCottageId.setEditable(false);
        txtCottageId.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtCottageId.setMargin(new java.awt.Insets(2, 5, 2, 5));

        txtCottageName.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtCottageName.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtCottageName.setPreferredSize(new java.awt.Dimension(164, 30));

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel2.setText("Cottage Name");

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel3.setText("Number of Rooms");

        txtNumOfRooms.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtNumOfRooms.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumOfRooms.setPreferredSize(new java.awt.Dimension(164, 30));

        txtAvailability.setEditable(false);
        txtAvailability.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtAvailability.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtAvailability.setPreferredSize(new java.awt.Dimension(164, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel4.setText("Availability");

        btnClear.setBackground(new java.awt.Color(120, 120, 120));
        btnClear.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClear.setPreferredSize(new java.awt.Dimension(103, 25));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEdit.setPreferredSize(new java.awt.Dimension(103, 25));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(105, 205, 130));
        btnAdd.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdd.setPreferredSize(new java.awt.Dimension(103, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumOfRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCottageId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCottageName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtAvailability, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCottageId, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCottageName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumOfRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(35, 67, 67));

        tblCottageRecords.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        tblCottageRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cottage ID", "Cottage Name", "Number of Rooms", "Availability"
            }
        ));
        tblCottageRecords.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblCottageRecords.setRowHeight(25);
        tblCottageRecords.setSelectionBackground(new java.awt.Color(105, 205, 130));
        tblCottageRecords.setShowVerticalLines(false);
        tblCottageRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCottageRecordsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCottageRecords);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cottages List");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearTextboxes();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int cottageId = Integer.parseInt(txtCottageId.getText());
        String cottageName = txtCottageName.getText();
        int numOfRooms = Integer.parseInt(txtNumOfRooms.getText());
        if (cottageId != 0 && cottageName != null) {
            try {
                PreparedStatement p = con.prepareStatement("UPDATE `cottage` SET cottage_name=?, num_of_rooms=? WHERE cottage_id=?");
                
                p.setString(1, cottageName);
                p.setInt(2, numOfRooms);
                p.setInt(3, cottageId);
                
                int updatedRows = p.executeUpdate();
                if (updatedRows > 0)
                    JOptionPane.showMessageDialog(null, "Edit Successful!");
                else
                    JOptionPane.showMessageDialog(null, "Error! Unable to update.");
            }
            catch (Exception ex) {
                System.out.println("Error. " + ex);
                JOptionPane.showMessageDialog(null, "Error!" + ex);
            }
            displayRecords();
            clearTextboxes();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            PreparedStatement p;
            String cottageName;

            cottageName = txtCottageName.getText();
            String newSqlRow = "INSERT INTO `cottage`(`cottage_name`) VALUES (?)";
            p = con.prepareStatement(newSqlRow);
            p.setString(1, cottageName);
            int updatedRows = p.executeUpdate();

            if (updatedRows > 0)
                JOptionPane.showMessageDialog(null, "Record Saved Successfully!");
            else
                JOptionPane.showMessageDialog(null, "Error! Unable to add.");
        }
        catch (Exception ex) {
            System.out.println("Error. " + ex);
            JOptionPane.showMessageDialog(null, "Error!" + ex);
        }
        displayRecords();
        clearTextboxes();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblCottageRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCottageRecordsMouseClicked
        DefaultTableModel model = (DefaultTableModel)tblCottageRecords.getModel();
        int selectedRowIndex = tblCottageRecords.getSelectedRow();
        String cottageId = null, cottageName = null, numOfRooms = null, isAvailable = null;
        int column = 0;
        
        cottageId = model.getValueAt(selectedRowIndex, column).toString();
        cottageName = model.getValueAt(selectedRowIndex, column+1).toString();
        numOfRooms = model.getValueAt(selectedRowIndex, column+2).toString(); 
        isAvailable = model.getValueAt(selectedRowIndex, column+3).toString(); 
            
        txtCottageId.setText(cottageId);
        txtCottageName.setText(cottageName);
        txtNumOfRooms.setText(numOfRooms);
        txtAvailability.setText(isAvailable);
        
        String userRole = currentUser.getRole().toLowerCase();
        switch (userRole) {
            case "admin":
            case "general":
                btnAdd.setEnabled(false);
                btnAdd.setBackground(new Color(240, 240, 240));
                btnEdit.setEnabled(true);
                btnEdit.setBackground(new Color(80, 170, 195));
                break;
            case "audit":
                btnAdd.setEnabled(false);
                btnAdd.setBackground(new Color(240, 240, 240));
                btnEdit.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_tblCottageRecordsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCottageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable tblCottageRecords;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtCottageId;
    private javax.swing.JTextField txtCottageName;
    private javax.swing.JTextField txtNumOfRooms;
    // End of variables declaration//GEN-END:variables
}
